# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86c3baf9a9d950cc12b61c3c54663a228407cbd0a9aae7f12260a1a0dc26c3426f88a3146aa82c98fe9a0ad0faad9c1a24370f7f379f57222df1b86e9f2450ac

test:
  secret_key_base: a7342ab8101a7398c48372e5268d12c81bee5e9491166428d8bb5cfee1e697186c7e027153c3615f79cccc775cd3dd75e55a045921b9bbd6b0dd68ac21ec32ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
